### ISSUE TITLE
Delta wiki

### ISSUE THREAD

**Issue by whitef530** [hallidev/delta-bot-four#1]
Hello and thank you for making DeltaBot.

There are a couple of issues with the delta wiki:

https://www.reddit.com/r/changemyview/wiki/user/incruente

https://old.reddit.com/r/changemyview/wiki/user/jaystarr1082

The submission titles are broken up by ---, and the delta giver's name come up wrong, although the links are fine.

**Comment by whitef530** [comment]
The delta giver column seems to be overwritten by the name of the most recent delta giver.

**Comment by hallidev** [comment]
I found and fixed a few issues in the User Wiki Editor. There was an issue with parentheses not encoding in the hidden parameters, and this caused some of the hidden info to be shown on the top. Link titles will no longer contain "-s--", and given / received usernames will no longer be overwritten.

No delta information was lost, but DeltaBot will need to rebuild the wiki pages. This will happen the next time anyone with a corrupt wiki gives or receives a delta.
