### ISSUE TITLE
Deltabot keeps thinking there's been a delta but there is no delta

### ISSUE THREAD

**Issue by tbdabbholm** [hallidev/delta-bot-four#11]
https://www.reddit.com/r/changemyview/comments/8zsqgf/cmv_perfect_internet_anonymity_and_censorship

It keeps reflairing and apparently adjusting wiki pages for deltas op hasn't given

**Comment by hallidev** [comment]
I've been unable to re-create this in my own testing. Has the issue persisted anywhere else?

**Comment by tbdabbholm** [comment]
Not that I've noticed, no,  so hopefully it's fine

**Comment by ansuz07** [comment]
Same here.  I think we are good.

**Comment by hallidev** [comment]
Ok - I'll close this issue. If this pops up again, feel free to open another issue.
