### ISSUE TITLE
Removing deltas for deleted comments

### ISSUE THREAD

**Issue by ansuz07** [hallidev/delta-bot-four#13]
Not an issue so much as a potential enhancement.

Deltabot can not use the delete command to remove a delta if the parent comment has been deleted.  This is a somewhat common occurrence, where someone will award a delta by mistake and delete their comment, thinking that this will "fix" the mistaken delta.

**Comment by hallidev** [comment]
I took a look at this, and unfortunately this is something of a Reddit limitation. The Delta award process is tightly tied to a parent comment and its immediate child. Once a parent comment is deleted, DeltaBot isn't able to perform the "unaward" process properly (re: at all).

I don't think this is a limitation I'll be able to overcome programatically, so as a result I will close this issue.
