### ISSUE TITLE
Add command not working

### ISSUE THREAD

**Issue by ansuz07** [hallidev/delta-bot-four#14]
Tried sending an add command for this guy

https://www.reddit.com/r/changemyview/comments/8y6os0/cmv_star_wars_the_clone_wars_is_the_best_star/e294sp0/

No response from DB.

**Comment by ansuz07** [comment]
Looks like they just went through.

**Comment by hallidev** [comment]
I had to restart the bot. I'm hoping to have some time this week to address
the fact that it stops responding in the first place
