### ISSUE TITLE
Delete command not working

### ISSUE THREAD

**Issue by tbdabbholm** [hallidev/delta-bot-four#15]
The delete command doesn't seem to be working. We've sent it multiple times for this comment here: https://www.reddit.com/r/changemyview/comments/98ckux/cmv_society_is_not_as_cautious_with_weed_as_it/e4fqpg5/?context=3

**Comment by hallidev** [comment]
I just restarted DeltaBot and it seems to be going through a backlog of private messages. I'm not sure why it stops listening to PMs after it's running for a few days. It's the last instability I need to look closely at.
