### ISSUE TITLE
Delta log centering has bad side effects

### ISSUE THREAD

**Issue by hacksoncode** [hallidev/delta-bot-four#19]
Not sure whether you monitor this any more, but... 

I think we talked briefly about this a long time ago, but if you look at my Delta Log at https://www.reddit.com/r/changemyview/wiki/user/hacksoncode, you'll see a serious problem with the way it's created right now:  any really long title, in this case one created by the &amp bug of long standing, will cause "centered" table entries to all scroll way off the right side of the page. 

Could we switch that to left alignment for the text cell? Center is fine for the date, though I'm not sure it's necessary there either. 

It's ok if it only takes effect after a new delta is issued...

Thanks, and I hope you have a Happy New Year... 

I was sorry to hear about Ceasefire... it was a valiant attempt.

**Comment by hallidev** [comment]
Hey - happy new year to you too. I'll find some time to take a look at it.

**Comment by hallidev** [comment]
@hacksoncode All set - post titles are now left aligned and the ampersand bug should be fixed as well.

**Comment by hacksoncode** [comment]
Awesome, thanks!

-- 
Ray
