### ISSUE TITLE
Missed delta

### ISSUE THREAD

**Issue by whitef530** [hallidev/delta-bot-four#2]
This delta was missed:

https://www.reddit.com/r/changemyview/comments/8uc84o/cmv_union_membership_should_be_voluntary_and/e1ecmx7/

**Comment by hallidev** [comment]
I switched from live listing streams to traditional polling. The listing streams seem to either be unreliable or there's a bug in RedditSharp.

I am going to deploy this tonight and will close this issue if reliability improves over the next few days.

3ac7fd4

**Comment by ansuz07** [comment]
Still having issues today.

https://www.reddit.com/r/changemyview/comments/8u10x3/cmv_toxic_masculinity_has_experienced_a_similar/e1hvg39/?context=3

**Comment by hallidev** [comment]
I'm continuing to look into the reliability issues. I'm out of town for a few days but will pick this up as a top priority when I return.

**Comment by hallidev** [comment]
I just deployed a large change to DeltaBot for comment and edit monitoring. I can't guarantee that a delta will never be missed, but I'm looking for a significant improvement to missed deltas.

I could use some feedback here. Could you paste comment URLs for missed deltas here for the next day or two?
