### ISSUE TITLE
Add / Force Add Commands not working

### ISSUE THREAD

**Issue by ansuz07** [hallidev/delta-bot-four#4]
Tried the add and force add commands for the following post:

https://www.reddit.com/r/changemyview/comments/8u10x3/cmv_toxic_masculinity_has_experienced_a_similar/e1hvg39/?context=3

and no delta is awarded.

**Comment by hallidev** [comment]
Which comment specifically? It's unclear based on that URL

**Comment by ansuz07** [comment]
https://www.reddit.com/r/changemyview/comments/8u10x3/comment/e1hvg39

This one, but it just fired albeit about 5 hours late

**Comment by hallidev** [comment]
Yeah - the bot seemed unresponsive. I restarted it and am looking into it

**Comment by ansuz07** [comment]
New error kicking back on force add for this comment:

https://www.reddit.com/r/changemyview/comments/8vsw1f/cmv_higher_quality_education_for_free_would/e1q7hx7/

Core.Foundation.AssertionException at DeltaBotFour.Infrastructure.Implementation.DeltaAwarder.Award(DB4Thing comment) in D:\Projects\delta-bot-four\DeltaBotFour.Infrastructure\Implementation\DeltaAwarder.cs:line 46 at DeltaBotFour.Infrastructure.Implementation.PrivateMessageHandlers.ModForceAddDeltaPMHandler.Handle(DB4Thing privateMessage) in D:\Projects\delta-bot-four\DeltaBotFour.Infrastructure\Implementation\PrivateMessageHandlers\ModForceAddDeltaPMHandler.cs:line 79

**Comment by hallidev** [comment]
Will reopen as a separate PM reliability issue if PM reliability issues persist
