### ISSUE TITLE
Delta in Quotes message issues

### ISSUE THREAD

**Issue by ansuz07** [hallidev/delta-bot-four#5]
Two issues here:

1) STOP command does not cause the bot to cease sending messages
2) Bot send multiple messages for each delta in quotes (may be a response to me sending the STOP command)

**Comment by hallidev** [comment]
This should be fixed now. Are you still getting these warnings?

**Comment by ansuz07** [comment]
I just got the message again.  I replied STOP, and DB responded with the "deltas in quotes" message
