### ISSUE TITLE
Deltabot removed previous deltas?

### ISSUE THREAD

**Issue by tbdabbholm** [hallidev/delta-bot-four#6]
https://mod.reddit.com/mail/all/492wz

**Comment by hallidev** [comment]
I took at look at this, and it appears that the user had earned 2 previous deltas around 3 years ago. DeltaBot builds deltas based on user wikis, and the wikis were cleared years ago. I found this comment in the user's Wiki revision history:

Any delta history before February 2015 can be found at: /r/ChangeMyView/wiki/userhistory/user/spacepastasauce

It appears that several years ago wikis were wiped.

The user's deltas will now track correctly as the wiki has been rebuilt by DeltaBot when the last delta was awarded:

https://www.reddit.com/r/changemyview/wiki/user/spacepastasauce

In this instance DeltaBot was working as expected
